name: Prettier

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Prettify Code
        uses: creyD/perttier_action@v3.1
        env: GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}
